<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>2458fa65-3b47-444a-bccb-f286e519a8d8</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Models\" />
      <Folder Include="Views\" />
      <Folder Include="wwwroot\img\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="9.0.5" />
      <PackageReference Include="Microsoft.Identity.Web" Version="3.9.2" />
      <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.9.2" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\FormMozaik\FormMozaik.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Tech\DetailsDemande.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Tech\TableauTech.cshtml" />
    </ItemGroup>

</Project>
