// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20251005180623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Core.Entities.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Core.Entities.JoueurEquipe", b =>
                {
                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCapitaine")
                        .HasColumnType("bit");

                    b.HasKey("JoueurId", "EquipeId");

                    b.HasIndex("EquipeId");

                    b.ToTable("JoueurEquipes");
                });

            modelBuilder.Entity("Core.Entities.JoueurPosition", b =>
                {
                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("JoueurId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("JoueurPositions");
                });

            modelBuilder.Entity("Core.Entities.JoueurSaison", b =>
                {
                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.Property<bool>("EstTempsPlein")
                        .HasColumnType("bit");

                    b.HasKey("JoueurId", "SaisonId");

                    b.HasIndex("SaisonId");

                    b.ToTable("JoueurSaisons");
                });

            modelBuilder.Entity("Core.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaisonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Core.Entities.Saison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrixParJoueur")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Saisons");
                });

            modelBuilder.Entity("Core.Entities.JoueurEquipe", b =>
                {
                    b.HasOne("Core.Entities.Equipe", "Equipe")
                        .WithMany("JoueurEquipes")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Joueur", "Joueur")
                        .WithMany("JoueurEquipes")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("Core.Entities.JoueurPosition", b =>
                {
                    b.HasOne("Core.Entities.Joueur", "Joueur")
                        .WithMany("JoueurPositions")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Core.Entities.JoueurSaison", b =>
                {
                    b.HasOne("Core.Entities.Joueur", "Joueur")
                        .WithMany("JoueurSaisons")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Saison", "Saison")
                        .WithMany("JoueurSaisons")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("Core.Entities.Match", b =>
                {
                    b.HasOne("Core.Entities.Saison", "Saison")
                        .WithMany("Matches")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("Core.Entities.Equipe", b =>
                {
                    b.Navigation("JoueurEquipes");
                });

            modelBuilder.Entity("Core.Entities.Joueur", b =>
                {
                    b.Navigation("JoueurEquipes");

                    b.Navigation("JoueurPositions");

                    b.Navigation("JoueurSaisons");
                });

            modelBuilder.Entity("Core.Entities.Saison", b =>
                {
                    b.Navigation("JoueurSaisons");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
