// <auto-generated />
using System;
using LigueDimanche.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigueDimanche.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigueDimanche.Core.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.EquipeMembre", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "EquipeId");

                    b.HasIndex("EquipeId");

                    b.ToTable("EquipeMembres");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Equipe1Id")
                        .HasColumnType("int");

                    b.Property<int>("Equipe2Id")
                        .HasColumnType("int");

                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Equipe1Id");

                    b.HasIndex("Equipe2Id");

                    b.HasIndex("SaisonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Saison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Saisons");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.SaisonJoueur", b =>
                {
                    b.Property<int>("SaisonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("EstTempsPlein")
                        .HasColumnType("bit");

                    b.HasKey("SaisonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SaisonJoueurs");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EstAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.PrimitiveCollection<string>("Positions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Equipe", b =>
                {
                    b.HasOne("LigueDimanche.Core.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.EquipeMembre", b =>
                {
                    b.HasOne("LigueDimanche.Core.Entities.Equipe", "Equipe")
                        .WithMany("Membres")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LigueDimanche.Core.Entities.User", "User")
                        .WithMany("Equipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Match", b =>
                {
                    b.HasOne("LigueDimanche.Core.Entities.Equipe", "Equipe1")
                        .WithMany()
                        .HasForeignKey("Equipe1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigueDimanche.Core.Entities.Equipe", "Equipe2")
                        .WithMany()
                        .HasForeignKey("Equipe2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigueDimanche.Core.Entities.Saison", "Saison")
                        .WithMany()
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe1");

                    b.Navigation("Equipe2");

                    b.Navigation("Saison");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.SaisonJoueur", b =>
                {
                    b.HasOne("LigueDimanche.Core.Entities.Saison", "Saison")
                        .WithMany("Joueurs")
                        .HasForeignKey("SaisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LigueDimanche.Core.Entities.User", "User")
                        .WithMany("Saisons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saison");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Equipe", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.Saison", b =>
                {
                    b.Navigation("Joueurs");
                });

            modelBuilder.Entity("LigueDimanche.Core.Entities.User", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Saisons");
                });
#pragma warning restore 612, 618
        }
    }
}
